export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const ADD_PRICE = 'ADD_PRICE';
export const SUBSTRACT_INGREDIENT = 'SUBSTRACT_INGREDIENT';
export const SUBSTRACT_PRICE = 'SUBSTRACT_PRICE';
export const SET_ORDERS = 'SET_ORDERS';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_PURCHASED = 'SET_IS_PURCHASED';
